const fs = require('fs');
const csv = require('csvtojson');

const inputFile = '/workspaces/A/Outscraper-20250309212621xs46_hvac_contractor - Generated by Outscraper © (1).csv';
const outputFile = '/workspaces/A/hvacbirmingham.json';

// Convert CSV to JSON
csv()
  .fromFile(inputFile)
  .then((jsonArray) => {
    // Create a simple map of business slugs to phone numbers
    const phoneMap = {};
    
    jsonArray.forEach(business => {
      if (business.name) {
        // Create slug from business name (lowercase, no special chars, spaces removed)
        const slug = business.name
          .toLowerCase()
          .replace(/[^\w\s]/gi, '')
          .replace(/\s+/g, '');
        
        // Add business name and phone DIRECTLY as a string value (not an object)
        phoneMap[slug] = {
          name: business.name,
          phone: business.phone  // This will be the actual phone string like "+1 205-251-0330"
        };
      }
    });
    
    // Write to file
    fs.writeFileSync(outputFile, JSON.stringify(phoneMap, null, 2));
    console.log(`Created phone mapping at ${outputFile}`);
  })
  .catch(err => {
    console.error('Error:', err);
  });